name: Fetch latest releases from GitHub

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-casks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Import GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set up GPG
        run: |
          gpg --list-secret-keys --keyid-format LONG
          export GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep 'sec' | awk '{print $2}' | cut -d'/' -f2)
          git config --global user.signingkey $GPG_KEY_ID
          git config --global commit.gpgSign true
          gpg --list-secret-keys --keyid-format LONG
        shell: bash

      - name: Make executable
        run: |
          chmod +x scripts/*.sh

      - name: Process casks
        run: ./scripts/process-casks.sh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO_OWNER: "${{ github.repository_owner }}"
          REPO_NAME: "${{ github.repository }}"
